apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJMU1EY3lOVEF3TkRBeU4xb1lEekl4TWpVd056QXhNREEwTURJM1dqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjFzelNZdzZlMTBzUEVnZ3Ezb3JKWnhFcUtrR1RZdlR1K0RBL3pWelBML2J3SXlIRTJDL21LQVVqN3haREdGT1MKbkJCUis0OG5icHBoMVJLZzc0dmZuaTdBK0poSzQ0ODFTM2FPOVlEVzI0RlRGWi90dDl5ZHJYbnRiZkxzcUcwWApFYUJzeE55UDU4UkFSTDFnbER1T2x1SGRjRm5kWW8wVkw1SzZhZkdyL3ZVY2lIS29pTDZOQjZLa3FBUkZubFpyCllESUV0VFhiR0xpU1I3TFkyeVVyN3RUM2dNc3JTUVJQQ3hOYmZiNzJhMjEzWXM2M3o3eGRvUFFvOTJxNmZIdHMKZ1NUZ1ZpcjgyNWs4ek1MTUovdWFBRmdob1FOL2RmU0FySTdZclRPUnpHZ2RvekozeS9ZTkFoRzRNRnpUdWJOSQpIeGZZWTdXZ1NOL2wxTVRKMi9lK1F3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVSclhNVDR6a2lXTlN3K0VBMUthS2dySkpraGN3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFLYzVTc1pURDBLNmIrZ01VQkd3cVFOOEFWWGw0NFEvekFjOGJVVkdnQXZzQXI3KwpIb0NRMllwS1J4MWllVkRrcGVXZkhmaU43clNnYWtVNmcycS9naUpHQktwOGVzSDBaM1pCaVJBamtaOENzcFZuCkwzS0FJQkhNTEYvYVRKYjNTNGFZNWZIZURHMmN0S0NnSmljT2lJdThoeWRXaVZRMzlWRWVtbUR6RnRBTXA3dHEKbXNUWXZGM3hoVVp6cGl1MFpyb1pzUDluOWlQZ2pHTWpkbFVuaTBzMFNmcDRTS3FURXZYWjhVcGU4MTRUbTBkZApFMm5sSE5DRTI2VGJUKzRJUW1pYzNFcmZqeTBzczQzN3FFTmFMbWg1bkhSbXRrTUpWbm1USUJkYlh4aGRWc1RZCklQeEx6RDNNaXJWU3o2cENmL29aTlp1aWk0WWpsVjhkZFI1ZW9jcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://256e2f2f-9005-46d1-a06d-2c45e8b35ef9.kr.vnks.gov-ntruss.com
  name: nks_kr_kps-public-image-hub_256e2f2f-9005-46d1-a06d-2c45e8b35ef9
contexts:
- context:
    cluster: nks_kr_kps-public-image-hub_256e2f2f-9005-46d1-a06d-2c45e8b35ef9
    user: nks_kr_kps-public-image-hub_256e2f2f-9005-46d1-a06d-2c45e8b35ef9
  name: nks_kr_kps-public-image-hub_256e2f2f-9005-46d1-a06d-2c45e8b35ef9
current-context: nks_kr_kps-public-image-hub_256e2f2f-9005-46d1-a06d-2c45e8b35ef9
kind: Config
preferences: {}
users:
- name: nks_kr_kps-public-image-hub_256e2f2f-9005-46d1-a06d-2c45e8b35ef9
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - --clusterUuid
      - 256e2f2f-9005-46d1-a06d-2c45e8b35ef9
      - --region
      - KR
      command: ncp-iam-authenticator
      env: null
      provideClusterInfo: false
